In [3]:
import pandas as pd

##### loading dataset

In [4]:
train_customers=pd.read_csv(r"C:\Users\AKSHAY KUMAR\akshay's folder\flm ds genai\project-5\Train\train_customers.csv")
train_customers

      customer_id gender  dob  ...  language       created_at       updated_at
0         TCHWPBT   Male  NaN  ...        EN   2/7/2023 19:16   2/7/2023 19:16
1         ZGFSYCZ   Male  NaN  ...        EN   2/9/2023 12:04   2/9/2023 12:04
2         S2ALZFL   Male  NaN  ...        EN  3/14/2023 18:31  3/14/2023 18:31
3         952DBJQ   Male  NaN  ...        EN  3/15/2023 19:47  3/15/2023 19:47
4         1IX6FXS   Male  NaN  ...        EN  3/15/2023 19:57  3/15/2023 19:57
...           ...    ...  ...  ...       ...              ...              ...
34669     JAI79PE    NaN  NaN  ...       NaN   3/3/2025 13:01   3/3/2025 13:02
34670     TR75VFL    NaN  NaN  ...       NaN   3/3/2025 13:22   3/3/2025 13:22
34671     SQMJ08H    NaN  NaN  ...       NaN   3/3/2025 13:24   3/3/2025 13:24
34672     9LW9CHN    NaN  NaN  ...       NaN   3/3/2025 13:24   3/3/2025 13:28
34673     LBMRK7A    NaN  NaN  ...       NaN   3/3/2025 13:31   3/3/2025 13:32

[34674 rows x 8 columns]

In [5]:
train_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34674 entries, 0 to 34673
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  34674 non-null  object
 1   gender       22520 non-null  object
 2   dob          3046 non-null   float64
 3   status       34674 non-null  int64
 4   verified     34674 non-null  int64
 5   language     21099 non-null  object
 6   created_at   34674 non-null  object
 7   updated_at   34674 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.1+ MB

##### cleaning data

In [6]:
train_customers["gender"]=train_customers["gender"].fillna("Unknown")
train_customers["language"]=train_customers["language"].fillna("Unknown")
train_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34674 entries, 0 to 34673
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  34674 non-null  object
 1   gender       34674 non-null  object
 2   dob          3046 non-null   float64
 3   status       34674 non-null  int64
 4   verified     34674 non-null  int64
 5   language     34674 non-null  object
 6   created_at   34674 non-null  object
 7   updated_at   34674 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.1+ MB

In [7]:
train_customers=train_customers.drop(columns=["dob","status","verified","created_at","updated_at"])
train_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34674 entries, 0 to 34673
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  34674 non-null  object
 1   gender       34674 non-null  object
 2   language     34674 non-null  object
dtypes: object(3)
memory usage: 812.8+ KB

In [8]:
train_customers

      customer_id   gender language
0         TCHWPBT     Male       EN
1         ZGFSYCZ     Male       EN
2         S2ALZFL     Male       EN
3         952DBJQ     Male       EN
4         1IX6FXS     Male       EN
...           ...      ...      ...
34669     JAI79PE  Unknown  Unknown
34670     TR75VFL  Unknown  Unknown
34671     SQMJ08H  Unknown  Unknown
34672     9LW9CHN  Unknown  Unknown
34673     LBMRK7A  Unknown  Unknown

[34674 rows x 3 columns]

In [9]:
train_customers["customer_id"].duplicated().sum()

np.int64(151)

In [10]:
train_customers=train_customers.drop_duplicates(subset=["customer_id"],keep="first")
train_customers

      customer_id   gender language
0         TCHWPBT     Male       EN
1         ZGFSYCZ     Male       EN
2         S2ALZFL     Male       EN
3         952DBJQ     Male       EN
4         1IX6FXS     Male       EN
...           ...      ...      ...
34669     JAI79PE  Unknown  Unknown
34670     TR75VFL  Unknown  Unknown
34671     SQMJ08H  Unknown  Unknown
34672     9LW9CHN  Unknown  Unknown
34673     LBMRK7A  Unknown  Unknown

[34523 rows x 3 columns]

In [11]:
train_customers["customer_id"].duplicated().sum()

np.int64(0)

In [12]:
train_customers

      customer_id   gender language
0         TCHWPBT     Male       EN
1         ZGFSYCZ     Male       EN
2         S2ALZFL     Male       EN
3         952DBJQ     Male       EN
4         1IX6FXS     Male       EN
...           ...      ...      ...
34669     JAI79PE  Unknown  Unknown
34670     TR75VFL  Unknown  Unknown
34671     SQMJ08H  Unknown  Unknown
34672     9LW9CHN  Unknown  Unknown
34673     LBMRK7A  Unknown  Unknown

[34523 rows x 3 columns]

In [13]:
train_locations=pd.read_csv(r"C:\Users\AKSHAY KUMAR\akshay's folder\flm ds genai\project-5\Train\train_locations.csv")
train_locations

      customer_id  location_number location_type  latitude  longitude
0         02SFNJH                0           NaN  1.682392 -78.789737
1         02SFNJH                1           NaN  1.679137   0.766823
2         02SFNJH                2           NaN -0.498648   0.661241
3         RU43CXC                0          Home  0.100853   0.438165
4         BDFBPRD                0           NaN  2.523125   0.733464
...           ...              ...           ...       ...        ...
59498     9PP42SA                2           NaN -0.788515 -78.497721
59499     9PP42SA                3          Home -1.445114   0.072558
59500     9PP42SA                4           NaN -0.001785   0.431695
59501     HWELAU8                0           NaN -0.066291 -78.583075
59502     HWELAU8                1           NaN -0.067043   0.648221

[59503 rows x 5 columns]

In [14]:
train_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59503 entries, 0 to 59502
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      59503 non-null  object
 1   location_number  59503 non-null  int64
 2   location_type    32294 non-null  object
 3   latitude         59497 non-null  float64
 4   longitude        59497 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.3+ MB

In [15]:
train_locations.duplicated().sum()

np.int64(0)

In [16]:
train_locations.isnull().sum()

customer_id            0
location_number        0
location_type      27209
latitude               6
longitude              6
dtype: int64

In [17]:
train_locations["location_type"]=train_locations["location_type"].fillna("Unknown")
train_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59503 entries, 0 to 59502
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      59503 non-null  object
 1   location_number  59503 non-null  int64
 2   location_type    59503 non-null  object
 3   latitude         59497 non-null  float64
 4   longitude        59497 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.3+ MB

In [18]:
train_locations=train_locations.dropna(subset=["latitude","longitude"])
train_locations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59497 entries, 0 to 59502
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      59497 non-null  object
 1   location_number  59497 non-null  int64
 2   location_type    59497 non-null  object
 3   latitude         59497 non-null  float64
 4   longitude        59497 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.7+ MB

In [19]:
train_locations

      customer_id  location_number location_type  latitude  longitude
0         02SFNJH                0       Unknown  1.682392 -78.789737
1         02SFNJH                1       Unknown  1.679137   0.766823
2         02SFNJH                2       Unknown -0.498648   0.661241
3         RU43CXC                0          Home  0.100853   0.438165
4         BDFBPRD                0       Unknown  2.523125   0.733464
...           ...              ...           ...       ...        ...
59498     9PP42SA                2       Unknown -0.788515 -78.497721
59499     9PP42SA                3          Home -1.445114   0.072558
59500     9PP42SA                4       Unknown -0.001785   0.431695
59501     HWELAU8                0       Unknown -0.066291 -78.583075
59502     HWELAU8                1       Unknown -0.067043   0.648221

[59497 rows x 5 columns]

In [20]:
train_orders=pd.read_csv(r"C:\Users\AKSHAY KUMAR\akshay's folder\flm ds genai\project-5\Train\orders.csv")
train_orders

C:\Users\AKSHAY KUMAR\AppData\Local\Temp\ipykernel_10508\3164560152.py:1: DtypeWarning: Columns (15,16,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  train_orders=pd.read_csv(r"C:\Users\AKSHAY KUMAR\akshay's folder\flm ds genai\project-5\Train\orders.csv")

        order_id customer_id  ...  LOCATION_TYPE  CID X LOC_NUM X VENDOR
0       163923.0     KL09J9N  ...           Work        KL09J9N X 0 X 84
1       163924.0     H5LGGFX  ...           Home        H5LGGFX X 0 X 78
2       163925.0     CYLZB6T  ...           Work         CYLZB6T X 0 X 4
3       163929.0     4YKUKYN  ...           Home       4YKUKYN X 0 X 157
4       163930.0     WDNU30K  ...           Home       WDNU30K X 0 X 160
...          ...         ...  ...            ...                     ...
135298  163914.0     YZNHLAP  ...          Other       YZNHLAP X 0 X 106
135299  163916.0     OD336VP  ...           Work       OD336VP X 0 X 105
135300  163917.0     N4F5VWP  ...           Work        N4F5VWP X 0 X 66
135301  163920.0     QURUHAI  ...           Work        QURUHAI X 0 X 81
135302  163921.0     FP6IQUM  ...           Work       FP6IQUM X 0 X 159

[135303 rows x 26 columns]

In [21]:
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   order_id                        135233 non-null  float64
 1   customer_id                     135303 non-null  object
 2   item_count                      128378 non-null  float64
 3   grand_total                     135303 non-null  float64
 4   payment_mode                    135303 non-null  int64
 5   promo_code                      4305 non-null    object
 6   vendor_discount_amount          135303 non-null  float64
 7   promo_code_discount_percentage  65880 non-null   float64
 8   is_favorite                     100108 non-null  object
 9   is_rated                        135303 non-null  object
 10  vendor_rating                   45220 non-null   float64
 11  driver_rating                   135303 non-null  int64
 12  deliverydistance                135303 non-null  float64
 13  preparationtime                 79743 non-null   float64
 14  delivery_time                   5123 non-null    object
 15  order_accepted_time             86955 non-null   object
 16  driver_accepted_time            46458 non-null   object
 17  ready_for_pickup_time           84249 non-null   object
 18  picked_up_time                  83865 non-null   object
 19  delivered_time                  85741 non-null   object
 20  delivery_date                   35544 non-null   object
 21  vendor_id                       135303 non-null  int64
 22  created_at                      135303 non-null  object
 23  LOCATION_NUMBER                 135303 non-null  int64
 24  LOCATION_TYPE                   86410 non-null   object
 25  CID X LOC_NUM X VENDOR          135303 non-null  object
dtypes: float64(8), int64(4), object(14)
memory usage: 26.8+ MB

In [22]:
## removing unnecessary column

train_orders=train_orders.drop(columns=["order_id","promo_code","promo_code_discount_percentage","delivery_time","order_accepted_time","driver_accepted_time","ready_for_pickup_time","picked_up_time","delivered_time","delivery_date","created_at","CID X LOC_NUM X VENDOR","is_favorite","is_rated","LOCATION_TYPE"])
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 11 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   customer_id             135303 non-null  object
 1   item_count              128378 non-null  float64
 2   grand_total             135303 non-null  float64
 3   payment_mode            135303 non-null  int64
 4   vendor_discount_amount  135303 non-null  float64
 5   vendor_rating           45220 non-null   float64
 6   driver_rating           135303 non-null  int64
 7   deliverydistance        135303 non-null  float64
 8   preparationtime         79743 non-null   float64
 9   vendor_id               135303 non-null  int64
 10  LOCATION_NUMBER         135303 non-null  int64
dtypes: float64(6), int64(4), object(1)
memory usage: 11.4+ MB

In [23]:
train_orders=train_orders.drop(columns=["payment_mode","vendor_discount_amount"])
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       135303 non-null  object
 1   item_count        128378 non-null  float64
 2   grand_total       135303 non-null  float64
 3   vendor_rating     45220 non-null   float64
 4   driver_rating     135303 non-null  int64
 5   deliverydistance  135303 non-null  float64
 6   preparationtime   79743 non-null   float64
 7   vendor_id         135303 non-null  int64
 8   LOCATION_NUMBER   135303 non-null  int64
dtypes: float64(5), int64(3), object(1)
memory usage: 9.3+ MB

In [24]:
train_orders.isnull().sum()

customer_id             0
item_count           6925
grand_total             0
vendor_rating       90083
driver_rating           0
deliverydistance        0
preparationtime     55560
vendor_id               0
LOCATION_NUMBER         0
dtype: int64

In [25]:
train_orders.describe()

          item_count    grand_total  ...      vendor_id  LOCATION_NUMBER
count  128378.000000  135303.000000  ...  135303.000000    135303.000000
mean        2.405404      15.374513  ...     239.214866         0.867527
std         1.645332      12.556177  ...     226.437406         1.239884
min         1.000000       0.000000  ...       4.000000         0.000000
25%         1.000000       8.200000  ...      84.000000         0.000000
50%         2.000000      11.700000  ...     157.000000         0.000000
75%         3.000000      18.500000  ...     299.000000         1.000000
max        68.000000     783.800000  ...     907.000000        25.000000

[8 rows x 8 columns]

In [26]:
## filling missing values in item_count

train_orders["item_count"]=train_orders["item_count"].fillna(train_orders["item_count"].median())
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       135303 non-null  object
 1   item_count        135303 non-null  float64
 2   grand_total       135303 non-null  float64
 3   vendor_rating     45220 non-null   float64
 4   driver_rating     135303 non-null  int64
 5   deliverydistance  135303 non-null  float64
 6   preparationtime   79743 non-null   float64
 7   vendor_id         135303 non-null  int64
 8   LOCATION_NUMBER   135303 non-null  int64
dtypes: float64(5), int64(3), object(1)
memory usage: 9.3+ MB

In [27]:
## filling missing_values in vendor_rating

train_orders["vendor_rating"]=train_orders["vendor_rating"].fillna(0)
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       135303 non-null  object
 1   item_count        135303 non-null  float64
 2   grand_total       135303 non-null  float64
 3   vendor_rating     135303 non-null  float64
 4   driver_rating     135303 non-null  int64
 5   deliverydistance  135303 non-null  float64
 6   preparationtime   79743 non-null   float64
 7   vendor_id         135303 non-null  int64
 8   LOCATION_NUMBER   135303 non-null  int64
dtypes: float64(5), int64(3), object(1)
memory usage: 9.3+ MB

In [28]:
train_orders["preparationtime"]=train_orders["preparationtime"].fillna(train_orders["preparationtime"].median())
train_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       135303 non-null  object
 1   item_count        135303 non-null  float64
 2   grand_total       135303 non-null  float64
 3   vendor_rating     135303 non-null  float64
 4   driver_rating     135303 non-null  int64
 5   deliverydistance  135303 non-null  float64
 6   preparationtime   135303 non-null  float64
 7   vendor_id         135303 non-null  int64
 8   LOCATION_NUMBER   135303 non-null  int64
dtypes: float64(5), int64(3), object(1)
memory usage: 9.3+ MB

In [29]:
train_orders.isnull().sum()

customer_id         0
item_count          0
grand_total         0
vendor_rating       0
driver_rating       0
deliverydistance    0
preparationtime     0
vendor_id           0
LOCATION_NUMBER     0
dtype: int64

In [30]:
train_orders

       customer_id  item_count  ...  vendor_id  LOCATION_NUMBER
0          KL09J9N         6.0  ...         84                0
1          H5LGGFX         3.0  ...         78                0
2          CYLZB6T         4.0  ...          4                0
3          4YKUKYN         7.0  ...        157                0
4          WDNU30K         1.0  ...        160                0
...            ...         ...  ...        ...              ...
135298     YZNHLAP         2.0  ...        106                0
135299     OD336VP         7.0  ...        105                0
135300     N4F5VWP         3.0  ...         66                0
135301     QURUHAI         3.0  ...         81                0
135302     FP6IQUM         2.0  ...        159                0

[135303 rows x 9 columns]

In [31]:
train_vendors=pd.read_csv(r"C:\Users\AKSHAY KUMAR\akshay's folder\flm ds genai\project-5\Train\vendors.csv")
train_vendors

     id  authentication_id  ...  device_type  display_orders
0     4             118597  ...            3               1
1    13             118608  ...            3               1
2    20             118616  ...            3               1
3    23             118619  ...            3               1
4    28             118624  ...            3               1
..  ...                ...  ...          ...             ...
95  849             130455  ...            3               1
96  855             130463  ...            3               1
97  856             130464  ...            3               1
98  858             130468  ...            3               1
99  907             132953  ...            3               1

[100 rows x 59 columns]

In [32]:
train_vendors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    100 non-null    int64
 1   authentication_id     100 non-null    int64
 2   latitude              100 non-null    float64
 3   longitude             100 non-null    float64
 4   vendor_category_en    100 non-null    object
 5   vendor_category_id    100 non-null    int64
 6   delivery_charge       100 non-null    float64
 7   serving_distance      100 non-null    int64
 8   is_open               100 non-null    int64
 9   OpeningTime           91 non-null     object
 10  OpeningTime2          91 non-null     object
 11  prepration_time       100 non-null    int64
 12  commission            85 non-null     float64
 13  is_haked_delivering   100 non-null    object
 14  discount_percentage   100 non-null    int64
 15  status                100 non-null    int64
 16  verified              100 non-null    int64
 17  rank                  100 non-null    int64
 18  language              85 non-null     object
 19  vendor_rating         100 non-null    float64
 20  sunday_from_time1     99 non-null     object
 21  sunday_to_time1       99 non-null     object
 22  sunday_from_time2     42 non-null     object
 23  sunday_to_time2       42 non-null     object
 24  monday_from_time1     100 non-null    object
 25  monday_to_time1       100 non-null    object
 26  monday_from_time2     42 non-null     object
 27  monday_to_time2       42 non-null     object
 28  tuesday_from_time1    99 non-null     object
 29  tuesday_to_time1      99 non-null     object
 30  tuesday_from_time2    41 non-null     object
 31  tuesday_to_time2      41 non-null     object
 32  wednesday_from_time1  100 non-null    object
 33  wednesday_to_time1    100 non-null    object
 34  wednesday_from_time2  42 non-null     object
 35  wednesday_to_time2    42 non-null     object
 36  thursday_from_time1   99 non-null     object
 37  thursday_to_time1     99 non-null     object
 38  thursday_from_time2   42 non-null     object
 39  thursday_to_time2     42 non-null     object
 40  friday_from_time1     96 non-null     object
 41  friday_to_time1       96 non-null     object
 42  friday_from_time2     45 non-null     object
 43  friday_to_time2       45 non-null     object
 44  saturday_from_time1   98 non-null     object
 45  saturday_to_time1     98 non-null     object
 46  saturday_from_time2   42 non-null     object
 47  saturday_to_time2     42 non-null     object
 48  primary_tags          77 non-null     object
 49  open_close_flags      100 non-null    int64
 50  vendor_tag            97 non-null     object
 51  vendor_tag_name       97 non-null     object
 52  one_click_vendor      100 non-null    object
 53  country_id            100 non-null    int64
 54  city_id               100 non-null    int64
 55  created_at            100 non-null    object
 56  updated_at            100 non-null    object
 57  device_type           100 non-null    int64
 58  display_orders        100 non-null    int64
dtypes: float64(5), int64(15), object(39)
memory usage: 46.2+ KB

In [33]:
train_vendors=train_vendors[["id","latitude","longitude","vendor_category_en","delivery_charge","serving_distance","is_open","prepration_time","vendor_rating"]]
train_vendors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  100 non-null    int64
 1   latitude            100 non-null    float64
 2   longitude           100 non-null    float64
 3   vendor_category_en  100 non-null    object
 4   delivery_charge     100 non-null    float64
 5   serving_distance    100 non-null    int64
 6   is_open             100 non-null    int64
 7   prepration_time     100 non-null    int64
 8   vendor_rating       100 non-null    float64
dtypes: float64(4), int64(4), object(1)
memory usage: 7.2+ KB

In [34]:
train_vendors=train_vendors.rename(columns={"id":"vendor_id"})
train_vendors

    vendor_id   latitude  longitude  ... is_open  prepration_time  vendor_rating
0           4  -0.588596   0.754434  ...       1               15            4.4
1          13  -0.471654   0.744470  ...       1               14            4.7
2          20  -0.407527   0.643681  ...       1               19            4.5
3          23  -0.585385   0.753811  ...       1               16            4.5
4          28   0.480602   0.552850  ...       1               10            4.4
..        ...        ...        ...  ...     ...              ...            ...
95        849  -1.588060  -0.066441  ...       1               10            4.1
96        855   2.145206   0.745025  ...       1               10            4.2
97        856   0.251469   0.483633  ...       1               10            4.3
98        858   0.019817   0.587087  ...       1               10            4.2
99        907  13.335131  -1.449556  ...       1               20            4.3

[100 rows x 9 columns]

In [35]:
train_vendors.isnull().sum()

vendor_id             0
latitude              0
longitude             0
vendor_category_en    0
delivery_charge       0
serving_distance      0
is_open               0
prepration_time       0
vendor_rating         0
dtype: int64

##### creating master dataframe by merging columns from across four dataframe

In [36]:
master_df=train_orders.merge(train_customers,on="customer_id",how="left")
master_df

       customer_id  item_count  grand_total  ...  LOCATION_NUMBER   gender  language
0          KL09J9N         6.0         10.1  ...                0     Male        EN
1          H5LGGFX         3.0          8.4  ...                0     Male        EN
2          CYLZB6T         4.0         15.0  ...                0     Male        EN
3          4YKUKYN         7.0         27.2  ...                0  Unknown        EN
4          WDNU30K         1.0          6.5  ...                0  Unknown        EN
...            ...         ...          ...  ...              ...      ...       ...
135298     YZNHLAP         2.0         25.0  ...                0   Female        EN
135299     OD336VP         7.0         53.0  ...                0  Unknown        EN
135300     N4F5VWP         3.0          8.5  ...                0  Unknown        EN
135301     QURUHAI         3.0         23.0  ...                0     Male        EN
135302     FP6IQUM         2.0         12.8  ...                0     Male        EN

[135303 rows x 11 columns]

In [37]:
master_df=master_df.merge(train_locations,left_on=["customer_id","LOCATION_NUMBER"],right_on=["customer_id","location_number"],how="left")
master_df

       customer_id  item_count  grand_total  ...  location_type  latitude  longitude
0          KL09J9N         6.0         10.1  ...           Work -0.090650 -78.580196
1          H5LGGFX         3.0          8.4  ...           Home  1.733950 -78.795830
2          CYLZB6T         4.0         15.0  ...           Work -0.368541 -78.547354
3          4YKUKYN         7.0         27.2  ...           Home  0.421104 -78.640676
4          WDNU30K         1.0          6.5  ...           Home -0.704372 -78.507665
...            ...         ...          ...  ...            ...       ...        ...
135298     YZNHLAP         2.0         25.0  ...          Other -0.151206 -78.573039
135299     OD336VP         7.0         53.0  ...           Work -1.081712 -78.463070
135300     N4F5VWP         3.0          8.5  ...           Work  1.123757 -78.723717
135301     QURUHAI         3.0         23.0  ...           Work  0.508867 -78.651048
135302     FP6IQUM         2.0         12.8  ...           Work  0.121891 -78.605314

[135303 rows x 15 columns]

In [38]:
master_df=master_df.merge(train_vendors,on="vendor_id",how="left")
master_df

       customer_id  item_count  ...  prepration_time  vendor_rating_y
0          KL09J9N         6.0  ...               14              4.3
1          H5LGGFX         3.0  ...               17              4.4
2          CYLZB6T         4.0  ...               15              4.4
3          4YKUKYN         7.0  ...               15              4.3
4          WDNU30K         1.0  ...               14              4.3
...            ...         ...  ...              ...              ...
135298     YZNHLAP         2.0  ...               10              4.5
135299     OD336VP         7.0  ...               12              4.5
135300     N4F5VWP         3.0  ...               20              4.0
135301     QURUHAI         3.0  ...               15              3.8
135302     FP6IQUM         2.0  ...               13              4.5

[135303 rows x 23 columns]

In [39]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   customer_id         135303 non-null  object
 1   item_count          135303 non-null  float64
 2   grand_total         135303 non-null  float64
 3   vendor_rating_x     135303 non-null  float64
 4   driver_rating       135303 non-null  int64
 5   deliverydistance    135303 non-null  float64
 6   preparationtime     135303 non-null  float64
 7   vendor_id           135303 non-null  int64
 8   LOCATION_NUMBER     135303 non-null  int64
 9   gender              132027 non-null  object
 10  language            132027 non-null  object
 11  location_number     135298 non-null  float64
 12  location_type       135298 non-null  object
 13  latitude_x          135298 non-null  float64
 14  longitude_x         135298 non-null  float64
 15  latitude_y          135303 non-null  float64
 16  longitude_y         135303 non-null  float64
 17  vendor_category_en  135303 non-null  object
 18  delivery_charge     135303 non-null  float64
 19  serving_distance    135303 non-null  int64
 20  is_open             135303 non-null  int64
 21  prepration_time     135303 non-null  int64
 22  vendor_rating_y     135303 non-null  float64
dtypes: float64(12), int64(6), object(5)
memory usage: 23.7+ MB

In [40]:
master_df.isnull().sum()

customer_id              0
item_count               0
grand_total              0
vendor_rating_x          0
driver_rating            0
deliverydistance         0
preparationtime          0
vendor_id                0
LOCATION_NUMBER          0
gender                3276
language              3276
location_number          5
location_type            5
latitude_x               5
longitude_x              5
latitude_y               0
longitude_y              0
vendor_category_en       0
delivery_charge          0
serving_distance         0
is_open                  0
prepration_time          0
vendor_rating_y          0
dtype: int64

In [41]:
master_df=master_df.drop(columns=["vendor_rating_x"])
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   customer_id         135303 non-null  object
 1   item_count          135303 non-null  float64
 2   grand_total         135303 non-null  float64
 3   driver_rating       135303 non-null  int64
 4   deliverydistance    135303 non-null  float64
 5   preparationtime     135303 non-null  float64
 6   vendor_id           135303 non-null  int64
 7   LOCATION_NUMBER     135303 non-null  int64
 8   gender              132027 non-null  object
 9   language            132027 non-null  object
 10  location_number     135298 non-null  float64
 11  location_type       135298 non-null  object
 12  latitude_x          135298 non-null  float64
 13  longitude_x         135298 non-null  float64
 14  latitude_y          135303 non-null  float64
 15  longitude_y         135303 non-null  float64
 16  vendor_category_en  135303 non-null  object
 17  delivery_charge     135303 non-null  float64
 18  serving_distance    135303 non-null  int64
 19  is_open             135303 non-null  int64
 20  prepration_time     135303 non-null  int64
 21  vendor_rating_y     135303 non-null  float64
dtypes: float64(11), int64(6), object(5)
memory usage: 22.7+ MB

In [42]:
master_df=master_df.rename(columns={"latitude_x":"customer_latitude","longitude_x":"customer_longitude","latitude_y":"vendor_latitude","longitude_y":"vendor_longitude","vendor_rating_y":"vendor_rating"})
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   customer_id         135303 non-null  object
 1   item_count          135303 non-null  float64
 2   grand_total         135303 non-null  float64
 3   driver_rating       135303 non-null  int64
 4   deliverydistance    135303 non-null  float64
 5   preparationtime     135303 non-null  float64
 6   vendor_id           135303 non-null  int64
 7   LOCATION_NUMBER     135303 non-null  int64
 8   gender              132027 non-null  object
 9   language            132027 non-null  object
 10  location_number     135298 non-null  float64
 11  location_type       135298 non-null  object
 12  customer_latitude   135298 non-null  float64
 13  customer_longitude  135298 non-null  float64
 14  vendor_latitude     135303 non-null  float64
 15  vendor_longitude    135303 non-null  float64
 16  vendor_category_en  135303 non-null  object
 17  delivery_charge     135303 non-null  float64
 18  serving_distance    135303 non-null  int64
 19  is_open             135303 non-null  int64
 20  prepration_time     135303 non-null  int64
 21  vendor_rating       135303 non-null  float64
dtypes: float64(11), int64(6), object(5)
memory usage: 22.7+ MB

In [43]:
master_df=master_df.drop(columns=["location_number"])
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135303 entries, 0 to 135302
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   customer_id         135303 non-null  object
 1   item_count          135303 non-null  float64
 2   grand_total         135303 non-null  float64
 3   driver_rating       135303 non-null  int64
 4   deliverydistance    135303 non-null  float64
 5   preparationtime     135303 non-null  float64
 6   vendor_id           135303 non-null  int64
 7   LOCATION_NUMBER     135303 non-null  int64
 8   gender              132027 non-null  object
 9   language            132027 non-null  object
 10  location_type       135298 non-null  object
 11  customer_latitude   135298 non-null  float64
 12  customer_longitude  135298 non-null  float64
 13  vendor_latitude     135303 non-null  float64
 14  vendor_longitude    135303 non-null  float64
 15  vendor_category_en  135303 non-null  object
 16  delivery_charge     135303 non-null  float64
 17  serving_distance    135303 non-null  int64
 18  is_open             135303 non-null  int64
 19  prepration_time     135303 non-null  int64
 20  vendor_rating       135303 non-null  float64
dtypes: float64(10), int64(6), object(5)
memory usage: 21.7+ MB

In [44]:
master_df.isnull().sum()

customer_id              0
item_count               0
grand_total              0
driver_rating            0
deliverydistance         0
preparationtime          0
vendor_id                0
LOCATION_NUMBER          0
gender                3276
language              3276
location_type            5
customer_latitude        5
customer_longitude       5
vendor_latitude          0
vendor_longitude         0
vendor_category_en       0
delivery_charge          0
serving_distance         0
is_open                  0
prepration_time          0
vendor_rating            0
dtype: int64

In [45]:
master_df["gender"]=master_df["gender"].fillna("Unknown")

In [46]:
master_df["language"]=master_df["language"].fillna("Unknown")

In [47]:
master_df["location_type"]=master_df["location_type"].fillna("Unknown")

In [48]:
master_df=master_df.dropna(subset=["customer_latitude","customer_longitude"])

In [49]:
master_df.isnull().sum()

customer_id           0
item_count            0
grand_total           0
driver_rating         0
deliverydistance      0
preparationtime       0
vendor_id             0
LOCATION_NUMBER       0
gender                0
language              0
location_type         0
customer_latitude     0
customer_longitude    0
vendor_latitude       0
vendor_longitude      0
vendor_category_en    0
delivery_charge       0
serving_distance      0
is_open               0
prepration_time       0
vendor_rating         0
dtype: int64

In [50]:
master_df

       customer_id  item_count  ...  prepration_time  vendor_rating
0          KL09J9N         6.0  ...               14            4.3
1          H5LGGFX         3.0  ...               17            4.4
2          CYLZB6T         4.0  ...               15            4.4
3          4YKUKYN         7.0  ...               15            4.3
4          WDNU30K         1.0  ...               14            4.3
...            ...         ...  ...              ...            ...
135298     YZNHLAP         2.0  ...               10            4.5
135299     OD336VP         7.0  ...               12            4.5
135300     N4F5VWP         3.0  ...               20            4.0
135301     QURUHAI         3.0  ...               15            3.8
135302     FP6IQUM         2.0  ...               13            4.5

[135298 rows x 21 columns]

### feature engineering

In [51]:

import numpy as np

In [52]:
## calculating distance from customer to vendor and adding it as column



def haversine(lat1,lon1,lat2,lon2):
    R=6371

    lat1,lon1,lat2,lon2=map(np.radians,[lat1,lon1,lat2,lon2])
    dlat=lat2-lat1
    dlon=lon2-lon1

    a=np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2

    c=2*np.arcsin(np.sqrt(a))

    return R*c

master_df["distance_km"]=haversine(master_df["customer_latitude"],master_df["customer_longitude"],master_df["vendor_latitude"],master_df["vendor_longitude"])

In [53]:
master_df

       customer_id  item_count  ...  vendor_rating  distance_km
0          KL09J9N         6.0  ...            4.3  8746.492036
1          H5LGGFX         3.0  ...            4.4  8786.057475
2          CYLZB6T         4.0  ...            4.4  8817.616529
3          4YKUKYN         7.0  ...            4.3  8803.808759
4          WDNU30K         1.0  ...            4.3  8737.667005
...            ...         ...  ...            ...          ...
135298     YZNHLAP         2.0  ...            4.5  8795.805186
135299     OD336VP         7.0  ...            4.5  8732.025675
135300     N4F5VWP         3.0  ...            4.0  8815.702055
135301     QURUHAI         3.0  ...            3.8  8753.508952
135302     FP6IQUM         2.0  ...            4.5  8824.815369

[135298 rows x 22 columns]

In [54]:
master_df=master_df.drop(columns=["customer_latitude","customer_longitude","vendor_latitude","vendor_longitude"])
master_df

       customer_id  item_count  ...  vendor_rating  distance_km
0          KL09J9N         6.0  ...            4.3  8746.492036
1          H5LGGFX         3.0  ...            4.4  8786.057475
2          CYLZB6T         4.0  ...            4.4  8817.616529
3          4YKUKYN         7.0  ...            4.3  8803.808759
4          WDNU30K         1.0  ...            4.3  8737.667005
...            ...         ...  ...            ...          ...
135298     YZNHLAP         2.0  ...            4.5  8795.805186
135299     OD336VP         7.0  ...            4.5  8732.025675
135300     N4F5VWP         3.0  ...            4.0  8815.702055
135301     QURUHAI         3.0  ...            3.8  8753.508952
135302     FP6IQUM         2.0  ...            4.5  8824.815369

[135298 rows x 18 columns]

In [55]:
## cleaning categorical columns

cat_cols=["gender","language","location_type","vendor_category_en"]

for col in cat_cols:
    master_df[col]=master_df[col].astype(str).str.strip().str.lower()

master_df

       customer_id  item_count  ...  vendor_rating  distance_km
0          KL09J9N         6.0  ...            4.3  8746.492036
1          H5LGGFX         3.0  ...            4.4  8786.057475
2          CYLZB6T         4.0  ...            4.4  8817.616529
3          4YKUKYN         7.0  ...            4.3  8803.808759
4          WDNU30K         1.0  ...            4.3  8737.667005
...            ...         ...  ...            ...          ...
135298     YZNHLAP         2.0  ...            4.5  8795.805186
135299     OD336VP         7.0  ...            4.5  8732.025675
135300     N4F5VWP         3.0  ...            4.0  8815.702055
135301     QURUHAI         3.0  ...            3.8  8753.508952
135302     FP6IQUM         2.0  ...            4.5  8824.815369

[135298 rows x 18 columns]

In [56]:
master_df["gender"].unique()

array(['male', 'unknown', 'female', ''], dtype=object)

In [57]:
master_df["language"].unique()

array(['en', 'unknown'], dtype=object)

In [58]:
master_df["location_type"].unique()

array(['work', 'home', 'other', 'unknown'], dtype=object)

In [59]:
master_df["vendor_category_en"].unique()

## probelm with sweets & bakes
## converting it into string without spaces and & symbol

array(['restaurants', 'sweets & bakes'], dtype=object)

In [60]:
master_df["vendor_category_en"]=(master_df["vendor_category_en"].astype(str)
                                 .str.strip()
                                 .str.lower()
                                 .str.replace("&","and")
                                 .str.replace(r"[^a-z0-9]+","_",regex=True)
                                 .str.strip("_"))

In [61]:
master_df["vendor_category_en"].unique()

array(['restaurants', 'sweets_and_bakes'], dtype=object)

In [62]:
## encoding categorical columns


from sklearn.preprocessing import OneHotEncoder
import numpy as np

oh_enc=OneHotEncoder()

cat_cols=["gender","language","location_type","vendor_category_en"]

encoded_oh=oh_enc.fit_transform(master_df[cat_cols])

encoded_cols=oh_enc.get_feature_names_out(cat_cols)

encoded_array=encoded_oh.toarray()

encoded_df=pd.DataFrame(encoded_array,columns=encoded_cols,index=master_df.index)

encoded_df

        gender_  ...  vendor_category_en_sweets_and_bakes
0           0.0  ...                                  0.0
1           0.0  ...                                  0.0
2           0.0  ...                                  0.0
3           0.0  ...                                  0.0
4           0.0  ...                                  0.0
...         ...  ...                                  ...
135298      0.0  ...                                  0.0
135299      0.0  ...                                  0.0
135300      0.0  ...                                  0.0
135301      0.0  ...                                  0.0
135302      0.0  ...                                  0.0

[135298 rows x 12 columns]

In [63]:
master_df_new=master_df.drop(columns=["gender","language","location_type","vendor_category_en"])
master_df_new

       customer_id  item_count  ...  vendor_rating  distance_km
0          KL09J9N         6.0  ...            4.3  8746.492036
1          H5LGGFX         3.0  ...            4.4  8786.057475
2          CYLZB6T         4.0  ...            4.4  8817.616529
3          4YKUKYN         7.0  ...            4.3  8803.808759
4          WDNU30K         1.0  ...            4.3  8737.667005
...            ...         ...  ...            ...          ...
135298     YZNHLAP         2.0  ...            4.5  8795.805186
135299     OD336VP         7.0  ...            4.5  8732.025675
135300     N4F5VWP         3.0  ...            4.0  8815.702055
135301     QURUHAI         3.0  ...            3.8  8753.508952
135302     FP6IQUM         2.0  ...            4.5  8824.815369

[135298 rows x 14 columns]

In [64]:
master_df_new=pd.concat([master_df_new,encoded_df],axis=1)
master_df_new

       customer_id  ...  vendor_category_en_sweets_and_bakes
0          KL09J9N  ...                                  0.0
1          H5LGGFX  ...                                  0.0
2          CYLZB6T  ...                                  0.0
3          4YKUKYN  ...                                  0.0
4          WDNU30K  ...                                  0.0
...            ...  ...                                  ...
135298     YZNHLAP  ...                                  0.0
135299     OD336VP  ...                                  0.0
135300     N4F5VWP  ...                                  0.0
135301     QURUHAI  ...                                  0.0
135302     FP6IQUM  ...                                  0.0

[135298 rows x 26 columns]

In [65]:
master_df_new.columns

Index(['customer_id', 'item_count', 'grand_total', 'driver_rating',
       'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER',
       'delivery_charge', 'serving_distance', 'is_open', 'prepration_time',
       'vendor_rating', 'distance_km', 'gender_', 'gender_female',
       'gender_male', 'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

In [66]:
master_df_new.columns

Index(['customer_id', 'item_count', 'grand_total', 'driver_rating',
       'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER',
       'delivery_charge', 'serving_distance', 'is_open', 'prepration_time',
       'vendor_rating', 'distance_km', 'gender_', 'gender_female',
       'gender_male', 'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

In [67]:
master_df["gender"].unique()

array(['male', 'unknown', 'female', ''], dtype=object)

In [68]:
(master_df["gender"]=="").sum()

np.int64(20)

In [69]:
master_df_new=master_df_new.drop(columns=["gender_"])
master_df_new

       customer_id  ...  vendor_category_en_sweets_and_bakes
0          KL09J9N  ...                                  0.0
1          H5LGGFX  ...                                  0.0
2          CYLZB6T  ...                                  0.0
3          4YKUKYN  ...                                  0.0
4          WDNU30K  ...                                  0.0
...            ...  ...                                  ...
135298     YZNHLAP  ...                                  0.0
135299     OD336VP  ...                                  0.0
135300     N4F5VWP  ...                                  0.0
135301     QURUHAI  ...                                  0.0
135302     FP6IQUM  ...                                  0.0

[135298 rows x 25 columns]

In [70]:
master_df_new.columns

Index(['customer_id', 'item_count', 'grand_total', 'driver_rating',
       'deliverydistance', 'preparationtime', 'vendor_id', 'LOCATION_NUMBER',
       'delivery_charge', 'serving_distance', 'is_open', 'prepration_time',
       'vendor_rating', 'distance_km', 'gender_female', 'gender_male',
       'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

##### model deployment

In [71]:
y=master_df_new["vendor_id"]

In [72]:
X=master_df_new.drop(columns=["customer_id","vendor_id"])

In [73]:
y.shape

(135298,)

In [74]:
X.shape

(135298, 23)

##### split data

In [75]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=26)

In [76]:
X_train

        item_count  ...  vendor_category_en_sweets_and_bakes
1594           3.0  ...                                  0.0
12114          2.0  ...                                  0.0
7536           3.0  ...                                  0.0
80925          1.0  ...                                  0.0
22451          1.0  ...                                  0.0
...            ...  ...                                  ...
71902          1.0  ...                                  0.0
116344         2.0  ...                                  1.0
75743          1.0  ...                                  0.0
58475          1.0  ...                                  0.0
54074          2.0  ...                                  1.0

[108238 rows x 23 columns]

In [77]:
X_test

        item_count  ...  vendor_category_en_sweets_and_bakes
49             1.0  ...                                  0.0
60898          2.0  ...                                  1.0
126736         4.0  ...                                  0.0
81936          2.0  ...                                  0.0
64450          5.0  ...                                  0.0
...            ...  ...                                  ...
88191          1.0  ...                                  0.0
107910         4.0  ...                                  0.0
3957           1.0  ...                                  0.0
47058          4.0  ...                                  1.0
18435          2.0  ...                                  0.0

[27060 rows x 23 columns]

In [78]:
y_train

1594      294
12114     304
7536      288
80925      84
22451      78
         ...
71902     573
116344     86
75743     157
58475      28
54074     386
Name: vendor_id, Length: 108238, dtype: int64

In [79]:
y_test

49        289
60898     386
126736    189
81936      79
64450      79
         ...
88191     134
107910    189
3957      113
47058     231
18435      78
Name: vendor_id, Length: 27060, dtype: int64

model creation

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [81]:
model=RandomForestClassifier(n_estimators=100,random_state=45)

In [82]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=45)

In [83]:
y_pred=model.predict(X_test)
y_pred

array([289, 386, 189, ..., 113, 231,  78])

In [84]:
from sklearn.metrics import accuracy_score

accuracy=accuracy_score(y_test,y_pred)

print("accuracy",accuracy)

accuracy 0.974390243902439

Creating customer-vendor pairs

Each row currently represents only the chosen vendor.
To enable comparison, we generate additional rows with other vendors as negative samples.

We convert each row into multiple rows:
* 1 positive (chosen vendor)
* multiple negative (not chosen vendors)

This helps the model learn how customers compare vendors

In [85]:
##  dropping data leakage columns

base_df=master_df_new.drop(columns=["customer_id","deliverydistance","preparationtime","prepration_time"])
base_df

        item_count  ...  vendor_category_en_sweets_and_bakes
0              6.0  ...                                  0.0
1              3.0  ...                                  0.0
2              4.0  ...                                  0.0
3              7.0  ...                                  0.0
4              1.0  ...                                  0.0
...            ...  ...                                  ...
135298         2.0  ...                                  0.0
135299         7.0  ...                                  0.0
135300         3.0  ...                                  0.0
135301         3.0  ...                                  0.0
135302         2.0  ...                                  0.0

[135298 rows x 21 columns]

In [86]:
base_df.columns

Index(['item_count', 'grand_total', 'driver_rating', 'vendor_id',
       'LOCATION_NUMBER', 'delivery_charge', 'serving_distance', 'is_open',
       'vendor_rating', 'distance_km', 'gender_female', 'gender_male',
       'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

In [87]:
customer_df=base_df.drop(columns=["vendor_category_en_sweets_and_bakes",
                                  "vendor_category_en_restaurants",
                                  "delivery_charge",
                                  "serving_distance",
                                  "is_open",
                                  "vendor_rating"])

customer_df

        item_count  grand_total  ...  location_type_unknown  location_type_work
0              6.0         10.1  ...                    0.0                 1.0
1              3.0          8.4  ...                    0.0                 0.0
2              4.0         15.0  ...                    0.0                 1.0
3              7.0         27.2  ...                    0.0                 0.0
4              1.0          6.5  ...                    0.0                 0.0
...            ...          ...  ...                    ...                 ...
135298         2.0         25.0  ...                    0.0                 0.0
135299         7.0         53.0  ...                    0.0                 1.0
135300         3.0          8.5  ...                    0.0                 1.0
135301         3.0         23.0  ...                    0.0                 1.0
135302         2.0         12.8  ...                    0.0                 1.0

[135298 rows x 15 columns]

In [88]:
customer_df.columns

Index(['item_count', 'grand_total', 'driver_rating', 'vendor_id',
       'LOCATION_NUMBER', 'distance_km', 'gender_female', 'gender_male',
       'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work'],
      dtype='object')

In [89]:
vendor_df = base_df[
    [
        'vendor_id',
        'vendor_rating',
        'delivery_charge',
        'serving_distance',
        'is_open',
        'vendor_category_en_restaurants',
        'vendor_category_en_sweets_and_bakes'
    ]
].drop_duplicates('vendor_id')

In [90]:
vendor_df

        vendor_id  ...  vendor_category_en_sweets_and_bakes
0              84  ...                                  0.0
1              78  ...                                  0.0
2               4  ...                                  0.0
3             157  ...                                  0.0
4             160  ...                                  0.0
...           ...  ...                                  ...
94369         845  ...                                  0.0
96360         843  ...                                  0.0
96399         856  ...                                  0.0
96412         855  ...                                  0.0
100781        907  ...                                  0.0

[100 rows x 7 columns]

In [91]:
vendor_df.columns

Index(['vendor_id', 'vendor_rating', 'delivery_charge', 'serving_distance',
       'is_open', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

In [92]:
## get all unique vendors

all_vendors=vendor_df["vendor_id"].unique()
all_vendors

array([ 84,  78,   4, 157, 160,  43, 294, 105, 104, 243,  83, 159,  55,
       231,  81, 300, 180,  13,  20, 303, 310, 289, 201, 265,  66, 192,
       145, 113, 134, 106, 110,  75,  82, 149, 176,  85, 154, 203, 274,
       115, 225, 193,  33,  92, 196, 221, 299, 207,  23, 288,  76, 161,
       298,  90, 199, 195, 271, 148, 304, 188, 259,  28, 197,  44, 189,
        79, 250, 191, 237, 356, 419, 391,  67,  86, 537, 459, 386, 295,
       401, 398, 216, 573, 575, 577, 578, 582, 583, 547, 679, 676, 681,
       841, 846, 858, 849, 845, 843, 856, 855, 907])

In [93]:
## pair creation

import random

rows=[]

for i,row in customer_df.iterrows():

    chosen_vendor=row["vendor_id"]

    # positive
    postve_rows=row.copy()
    postve_rows["Label"]=1
    rows.append(postve_rows)


    # negative

    negtve_vendors=random.sample(list(all_vendors),2)

    for v in negtve_vendors:
        if v==chosen_vendor:
            continue

        neg_row=row.copy()
        neg_row["vendor_id"]=v
        neg_row["Label"]=0
        rows.append(neg_row)

In [94]:
rows

[item_count                  6.000000
 grand_total                10.100000
 driver_rating               0.000000
 vendor_id                  84.000000
 LOCATION_NUMBER             0.000000
 distance_km              8746.492036
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       1.000000
 Name: 0, dtype: float64,
 item_count                  6.000000
 grand_total                10.100000
 driver_rating               0.000000
 vendor_id                  81.000000
 LOCATION_NUMBER             0.000000
 distance_km              8746.492036
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 0, dtype: float64,
 item_count                  6.000000
 grand_total                10.100000
 driver_rating               0.000000
 vendor_id                 575.000000
 LOCATION_NUMBER             0.000000
 distance_km              8746.492036
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 0, dtype: float64,
 item_count                  3.000000
 grand_total                 8.400000
 driver_rating               0.000000
 vendor_id                  78.000000
 LOCATION_NUMBER             0.000000
 distance_km              8786.057475
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       1.000000
 Name: 1, dtype: float64,
 item_count                  3.000000
 grand_total                 8.400000
 driver_rating               0.000000
 vendor_id                  28.000000
 LOCATION_NUMBER             0.000000
 distance_km              8786.057475
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 1, dtype: float64,
 item_count                  3.000000
 grand_total                 8.400000
 driver_rating               0.000000
 vendor_id                 459.000000
 LOCATION_NUMBER             0.000000
 distance_km              8786.057475
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 1, dtype: float64,
 item_count                  4.000000
 grand_total                15.000000
 driver_rating               0.000000
 vendor_id                   4.000000
 LOCATION_NUMBER             0.000000
 distance_km              8817.616529
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       1.000000
 Name: 2, dtype: float64,
 item_count                  4.000000
 grand_total                15.000000
 driver_rating               0.000000
 vendor_id                 134.000000
 LOCATION_NUMBER             0.000000
 distance_km              8817.616529
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 2, dtype: float64,
 item_count                  4.000000
 grand_total                15.000000
 driver_rating               0.000000
 vendor_id                 849.000000
 LOCATION_NUMBER             0.000000
 distance_km              8817.616529
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 2, dtype: float64,
 item_count                  7.000000
 grand_total                27.200000
 driver_rating               0.000000
 vendor_id                 157.000000
 LOCATION_NUMBER             0.000000
 distance_km              8803.808759
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       1.000000
 Name: 3, dtype: float64,
 item_count                  7.000000
 grand_total                27.200000
 driver_rating               0.000000
 vendor_id                 192.000000
 LOCATION_NUMBER             0.000000
 distance_km              8803.808759
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 3, dtype: float64,
 item_count                  7.000000
 grand_total                27.200000
 driver_rating               0.000000
 vendor_id                 459.000000
 LOCATION_NUMBER             0.000000
 distance_km              8803.808759
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 3, dtype: float64,
 item_count                  1.000000
 grand_total                 6.500000
 driver_rating               0.000000
 vendor_id                 160.000000
 LOCATION_NUMBER             0.000000
 distance_km              8737.667005
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       1.000000
 Name: 4, dtype: float64,
 item_count                  1.000000
 grand_total                 6.500000
 driver_rating               0.000000
 vendor_id                   4.000000
 LOCATION_NUMBER             0.000000
 distance_km              8737.667005
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 4, dtype: float64,
 item_count                  1.000000
 grand_total                 6.500000
 driver_rating               0.000000
 vendor_id                 193.000000
 LOCATION_NUMBER             0.000000
 distance_km              8737.667005
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 4, dtype: float64,
 item_count                  4.00000
 grand_total                15.50000
 driver_rating               0.00000
 vendor_id                  43.00000
 LOCATION_NUMBER             0.00000
 distance_km              8790.29901
 gender_female               0.00000
 gender_male                 0.00000
 gender_unknown              1.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          1.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          0.00000
 Label                       1.00000
 Name: 5, dtype: float64,
 item_count                  4.00000
 grand_total                15.50000
 driver_rating               0.00000
 vendor_id                 398.00000
 LOCATION_NUMBER             0.00000
 distance_km              8790.29901
 gender_female               0.00000
 gender_male                 0.00000
 gender_unknown              1.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          1.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          0.00000
 Label                       0.00000
 Name: 5, dtype: float64,
 item_count                  4.00000
 grand_total                15.50000
 driver_rating               0.00000
 vendor_id                 259.00000
 LOCATION_NUMBER             0.00000
 distance_km              8790.29901
 gender_female               0.00000
 gender_male                 0.00000
 gender_unknown              1.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          1.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          0.00000
 Label                       0.00000
 Name: 5, dtype: float64,
 item_count                  4.00000
 grand_total                15.00000
 driver_rating               0.00000
 vendor_id                  43.00000
 LOCATION_NUMBER             0.00000
 distance_km              8786.09412
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       1.00000
 Name: 6, dtype: float64,
 item_count                  4.00000
 grand_total                15.00000
 driver_rating               0.00000
 vendor_id                 294.00000
 LOCATION_NUMBER             0.00000
 distance_km              8786.09412
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       0.00000
 Name: 6, dtype: float64,
 item_count                  4.00000
 grand_total                15.00000
 driver_rating               0.00000
 vendor_id                 231.00000
 LOCATION_NUMBER             0.00000
 distance_km              8786.09412
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       0.00000
 Name: 6, dtype: float64,
 item_count                  2.000000
 grand_total                 9.200000
 driver_rating               0.000000
 vendor_id                  78.000000
 LOCATION_NUMBER             0.000000
 distance_km              8768.586711
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       1.000000
 Name: 7, dtype: float64,
 item_count                  2.000000
 grand_total                 9.200000
 driver_rating               0.000000
 vendor_id                 271.000000
 LOCATION_NUMBER             0.000000
 distance_km              8768.586711
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 7, dtype: float64,
 item_count                  2.000000
 grand_total                 9.200000
 driver_rating               0.000000
 vendor_id                 303.000000
 LOCATION_NUMBER             0.000000
 distance_km              8768.586711
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          0.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          1.000000
 Label                       0.000000
 Name: 7, dtype: float64,
 item_count                  2.00000
 grand_total                 8.40000
 driver_rating               0.00000
 vendor_id                  43.00000
 LOCATION_NUMBER             0.00000
 distance_km              8797.86643
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       1.00000
 Name: 8, dtype: float64,
 item_count                  2.00000
 grand_total                 8.40000
 driver_rating               0.00000
 vendor_id                 154.00000
 LOCATION_NUMBER             0.00000
 distance_km              8797.86643
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       0.00000
 Name: 8, dtype: float64,
 item_count                  2.00000
 grand_total                 8.40000
 driver_rating               0.00000
 vendor_id                 398.00000
 LOCATION_NUMBER             0.00000
 distance_km              8797.86643
 gender_female               0.00000
 gender_male                 1.00000
 gender_unknown              0.00000
 language_en                 1.00000
 language_unknown            0.00000
 location_type_home          0.00000
 location_type_other         0.00000
 location_type_unknown       0.00000
 location_type_work          1.00000
 Label                       0.00000
 Name: 8, dtype: float64,
 item_count                  3.000000
 grand_total                26.600000
 driver_rating               0.000000
 vendor_id                 294.000000
 LOCATION_NUMBER             0.000000
 distance_km              8717.102971
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       1.000000
 Name: 9, dtype: float64,
 item_count                  3.000000
 grand_total                26.600000
 driver_rating               0.000000
 vendor_id                 113.000000
 LOCATION_NUMBER             0.000000
 distance_km              8717.102971
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 9, dtype: float64,
 item_count                  3.000000
 grand_total                26.600000
 driver_rating               0.000000
 vendor_id                  90.000000
 LOCATION_NUMBER             0.000000
 distance_km              8717.102971
 gender_female               0.000000
 gender_male                 1.000000
 gender_unknown              0.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       0.000000
 Name: 9, dtype: float64,
 item_count                  3.000000
 grand_total                13.000000
 driver_rating               0.000000
 vendor_id                  78.000000
 LOCATION_NUMBER             0.000000
 distance_km              8774.794186
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000
 location_type_other         0.000000
 location_type_unknown       0.000000
 location_type_work          0.000000
 Label                       1.000000
 Name: 10, dtype: float64,
 item_count                  3.000000
 grand_total                13.000000
 driver_rating               0.000000
 vendor_id                 188.000000
 LOCATION_NUMBER             0.000000
 distance_km              8774.794186
 gender_female               0.000000
 gender_male                 0.000000
 gender_unknown              1.000000
 language_en                 1.000000
 language_unknown            0.000000
 location_type_home          1.000000

In [95]:
pairs_df=pd.DataFrame(rows)
pairs_df

        item_count  grand_total  ...  location_type_work  Label
0              6.0         10.1  ...                 1.0    1.0
0              6.0         10.1  ...                 1.0    0.0
0              6.0         10.1  ...                 1.0    0.0
1              3.0          8.4  ...                 0.0    1.0
1              3.0          8.4  ...                 0.0    0.0
...            ...          ...  ...                 ...    ...
135301         3.0         23.0  ...                 1.0    0.0
135301         3.0         23.0  ...                 1.0    0.0
135302         2.0         12.8  ...                 1.0    1.0
135302         2.0         12.8  ...                 1.0    0.0
135302         2.0         12.8  ...                 1.0    0.0

[403157 rows x 16 columns]

In [96]:
pairs_df.shape

(403157, 16)

In [97]:
pairs_df["Label"].value_counts()

Label
0.0    267859
1.0    135298
Name: count, dtype: int64

In [98]:
pairs_df.head()

   item_count  grand_total  ...  location_type_work  Label
0         6.0         10.1  ...                 1.0    1.0
0         6.0         10.1  ...                 1.0    0.0
0         6.0         10.1  ...                 1.0    0.0
1         3.0          8.4  ...                 0.0    1.0
1         3.0          8.4  ...                 0.0    0.0

[5 rows x 16 columns]

In [99]:
final_df=pairs_df.merge(vendor_df,on="vendor_id",how="left")
final_df

        item_count  ...  vendor_category_en_sweets_and_bakes
0              6.0  ...                                  0.0
1              6.0  ...                                  0.0
2              6.0  ...                                  1.0
3              3.0  ...                                  0.0
4              3.0  ...                                  0.0
...            ...  ...                                  ...
403152         3.0  ...                                  1.0
403153         3.0  ...                                  1.0
403154         2.0  ...                                  0.0
403155         2.0  ...                                  0.0
403156         2.0  ...                                  1.0

[403157 rows x 22 columns]

In [100]:
final_df.shape

(403157, 22)

In [101]:
final_df.columns

Index(['item_count', 'grand_total', 'driver_rating', 'vendor_id',
       'LOCATION_NUMBER', 'distance_km', 'gender_female', 'gender_male',
       'gender_unknown', 'language_en', 'language_unknown',
       'location_type_home', 'location_type_other', 'location_type_unknown',
       'location_type_work', 'Label', 'vendor_rating', 'delivery_charge',
       'serving_distance', 'is_open', 'vendor_category_en_restaurants',
       'vendor_category_en_sweets_and_bakes'],
      dtype='object')

In [102]:
X=final_df.drop(columns=["vendor_id","Label"])
y=final_df["Label"]

In [103]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=65)

In [104]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(random_state=43)

model.fit(X_train,y_train)

RandomForestClassifier(random_state=43)

In [105]:
y_pred=model.predict(X_test)

In [106]:
from sklearn.metrics import accuracy_score

accuracy=accuracy_score(y_test,y_pred)

print("accuracy",accuracy)

accuracy 0.81074511360254

In [107]:
from sklearn.metrics import classification_report,roc_auc_score

print(classification_report(y_test,y_pred))

y_prob=model.predict_proba(X_test)[:,1]

print("ROC-AUC",roc_auc_score(y_test,y_prob))

              precision    recall  f1-score   support

         0.0       0.84      0.89      0.86     53709
         1.0       0.75      0.65      0.70     26923

    accuracy                           0.81     80632
   macro avg       0.79      0.77      0.78     80632
weighted avg       0.81      0.81      0.81     80632

ROC-AUC 0.875233703073279

In [108]:
sample_customer=customer_df.iloc[0]

In [109]:
rows=[]

for v in vendor_df["vendor_id"]:
    row=sample_customer.copy()
    row["vendor_id"]=v
    rows.append(row)

test_df=pd.DataFrame(rows)

In [110]:
test_df = test_df.merge(vendor_df, on='vendor_id', how='left')

In [111]:
X_columns = X_train.columns

In [112]:
X_new = test_df[X_columns]

In [113]:
scores = model.predict_proba(X_new)[:, 1]
test_df['score'] = scores

In [114]:
top_vendors = test_df.sort_values(by='score', ascending=False).head(5)

top_vendors[['vendor_id', 'score']]

    vendor_id     score
10       83.0  0.786667
79      398.0  0.786667
55      195.0  0.786667
46      299.0  0.786667
70      419.0  0.786667

In [115]:
test_df[['vendor_id','vendor_rating','distance_km','delivery_charge']].head(10)

   vendor_id  vendor_rating  distance_km  delivery_charge
0       84.0            4.3  8746.492036              0.0
1       78.0            4.4  8746.492036              0.7
2        4.0            4.4  8746.492036              0.0
3      157.0            4.3  8746.492036              0.7
4      160.0            4.3  8746.492036              0.7
5       43.0            4.3  8746.492036              0.7
6      294.0            4.4  8746.492036              0.0
7      105.0            4.5  8746.492036              0.0
8      104.0            4.5  8746.492036              0.0
9      243.0            4.4  8746.492036              0.7